version: "3.8"
services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maets
      MYSQL_USER: maets
      MYSQL_PASSWORD: maets
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
